# Notebook 1: Read & join the tables

In [1]:
import sys
assert "olist_mlops" in sys.executable, f"wrong kernel selected in the editor - expected the olist_mlops env, got: {sys.executable}"

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

## connect to db and read the tables

In [3]:
engine = create_engine("postgresql+psycopg2://olist:olist@localhost:5432/olist")

ARTIFACTS_DIR = Path("artifacts")
ARTIFACTS_DIR.mkdir(exist_ok=True)

customers = pd.read_sql_table("customers", engine)
geolocation = pd.read_sql_table("geolocation", engine)
orders = pd.read_sql_table("orders", engine)
order_items = pd.read_sql_table("order_items", engine)
order_payments = pd.read_sql_table("order_payments", engine)
order_reviews = pd.read_sql_table("order_reviews", engine)
products = pd.read_sql_table("products", engine)
sellers = pd.read_sql_table("sellers", engine)
category_translation = pd.read_sql_table("category_translation", engine)

In [4]:
# check for every table: shape, duplicate keys, nulls, categorical counts

def explore(df, name, key_cols=None):
    print(f"--- {name} ---")
    print("shape:", df.shape)
    print("\ncolumn dtypes:")
    print(df.dtypes)
    if key_cols:
        print(f"\nduplicate rows on {key_cols}:", df.duplicated(subset=key_cols).sum())
    nulls = df.isna().sum()
    nulls = nulls[nulls > 0]
    if len(nulls):
        print("\nnulls per column:")
        print(nulls)
    for col in df.select_dtypes(include="object").columns:
        n_unique = df[col].nunique()
        if n_unique <= 30:
            print(f"\n{col} value counts:")
            print(df[col].value_counts(dropna=False))
        else:
            print(f"\n{col}: {n_unique} distinct values")
    print()

In [5]:
explore(customers, "customers", key_cols=["customer_id"])

--- customers ---
shape: (99441, 5)

column dtypes:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

duplicate rows on ['customer_id']: 0

customer_id: 99441 distinct values

customer_unique_id: 96096 distinct values

customer_city: 4119 distinct values

customer_state value counts:
customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [6]:
explore(orders, "orders", key_cols=["order_id"])

--- orders ---
shape: (99441, 8)

column dtypes:
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

duplicate rows on ['order_id']: 0

nulls per column:
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

order_id: 99441 distinct values

customer_id: 99441 distinct values

order_status value counts:

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [7]:
explore(order_items, "order_items", key_cols=["order_id", "order_item_id"])

--- order_items ---
shape: (112650, 7)

column dtypes:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

duplicate rows on ['order_id', 'order_item_id']: 0

order_id: 98666 distinct values

product_id: 32951 distinct values

seller_id: 3095 distinct values

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

shipping_limit_date: 93318 distinct values

In [8]:
explore(order_payments, "order_payments", key_cols=["order_id", "payment_sequential"])

--- order_payments ---
shape: (103886, 5)

column dtypes:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

duplicate rows on ['order_id', 'payment_sequential']: 0

order_id: 99440 distinct values

payment_type value counts:
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [9]:
explore(order_reviews, "order_reviews", key_cols=["review_id"])

--- order_reviews ---
shape: (99224, 7)

column dtypes:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

duplicate rows on ['review_id']: 814

nulls per column:
review_comment_title      87656
review_comment_message    58247
dtype: int64

review_id: 98410 distinct values

order_id: 98673 distinct values

review_comment_title: 4527 distinct values

review_comment_message: 36159 distinct values

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

review_creation_date: 636 distinct values

review_answer_timestamp: 98248 distinct values

In [10]:
explore(products, "products", key_cols=["product_id"])

--- products ---
shape: (32951, 9)

column dtypes:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

duplicate rows on ['product_id']: 0

nulls per column:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

product_id: 32951 distinct values

product_category_name: 73 distinct values

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [11]:
explore(sellers, "sellers", key_cols=["seller_id"])

--- sellers ---
shape: (3095, 4)

column dtypes:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

duplicate rows on ['seller_id']: 0

seller_id: 3095 distinct values

seller_city: 611 distinct values

seller_state value counts:
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [12]:
explore(category_translation, "category_translation", key_cols=["product_category_name"])

--- category_translation ---
shape: (71, 2)

column dtypes:
product_category_name            str
product_category_name_english    str
dtype: object

duplicate rows on ['product_category_name']: 0

product_category_name: 71 distinct values

product_category_name_english: 71 distinct values

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [13]:
explore(geolocation, "geolocation")

--- geolocation ---
shape: (1000163, 5)

column dtypes:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

C:\Users\ayham\AppData\Local\Temp\ipykernel_33068\3541798220.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

geolocation_city: 8011 distinct values

geolocation_state value counts:
geolocation_state
SP    404268
MG    126336
RJ    121169
RS     61851
PR     57859
SC     38328
BA     36045
GO     20139
ES     16748
PE     16432
DF     12986
MT     12031
CE     11674
PA     10853
MS     10431
MA      7853
PB      5538
RN      5041
PI      4549
AL      4183
TO      3576
SE      3563
RO      3478
AM      2432
AC      1301
AP       853
RR       646
Name: count, dtype: int64

## Aggregate

In [14]:
items_agg = order_items.groupby("order_id").agg(
    n_items=("order_item_id", "count"),
    n_distinct_products=("product_id", "nunique"),
    n_distinct_sellers=("seller_id", "nunique"),
    total_price=("price", "sum"),
    total_freight_value=("freight_value", "sum"),
    avg_item_price=("price", "mean"),
).reset_index()

items_agg.head()

,order_id,n_items,n_distinct_products,n_distinct_sellers,total_price,total_freight_value,avg_item_price
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.90,13.29,58.90
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,239.90,19.93,239.90
2,000229ec398224ef6ca0657da4fc703e,1,1,1,199.00,17.87,199.00
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,12.99,12.79,12.99
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,199.90,18.14,199.90

In [15]:
# main seller column, if the order have multi sellers we just add one based on total price
seller_price = (
    order_items.groupby(["order_id", "seller_id"])["price"]
    .sum()
    .reset_index()
    .sort_values("price", ascending=False)
)
main_seller = seller_price.drop_duplicates("order_id", keep="first")[["order_id", "seller_id"]]
main_seller = main_seller.rename(columns={"seller_id": "main_seller_id"})

main_seller.head()

                               order_id                    main_seller_id
1470   03caa2c082116e1d31e67e9ae3700499  b37c4c02bda3161a7546a4e6d222d5b2
45066  736e1922ae60d0d6a89247b851902527  b37c4c02bda3161a7546a4e6d222d5b2
3167   0812eb902a67711a1cb742b3cdaa65ae  e3b4998c7a498169dc7bce44e6bb6277
99638  fefacc66af859508bf1a7934eab1e97f  80ceebb4ee9b31afb6c6a916a574a1e2
95733  f5136e38d1a14a4dbd87dff67da82701  ee27a8f15b1dded4d213a468ba4eb391

In [16]:
# product info per item, so we can get weight and category per order

items_products = order_items.merge(
    products[["product_id", "product_category_name", "product_weight_g"]],
    on="product_id", how="left",
)

# one row per order: total weight
weight_agg = items_products.groupby("order_id").agg(
    total_weight_g=("product_weight_g", "sum"),
).reset_index()


# main category, category of the single highest-price item in the order
main_category = (
    items_products.sort_values("price", ascending=False)
    .drop_duplicates("order_id", keep="first")[["order_id", "product_category_name"]]
    .rename(columns={"product_category_name": "main_product_category"})
)

weight_agg.head()

                           order_id  total_weight_g
0  00010242fe8c5a6d1ba2dd792cb16214           650.0
1  00018f77f2f0320c557190d7a144bdd3         30000.0
2  000229ec398224ef6ca0657da4fc703e          3050.0
3  00024acbcdf0a6daa1e931b038114c75           200.0
4  00042b26cf59d7ce69dfabb4e55b4fd9          3750.0

In [17]:
# one row per order: payment totals
payments_agg = order_payments.groupby("order_id").agg(
    total_payment_value=("payment_value", "sum"),
    max_installments=("payment_installments", "max"),
    n_payment_methods=("payment_type", "nunique"),
).reset_index()

# main payment type, the first payment method used on the order
main_payment_type = (
    order_payments.sort_values("payment_sequential")
    .drop_duplicates("order_id", keep="first")[["order_id", "payment_type"]]
    .rename(columns={"payment_type": "main_payment_type"})
)

payments_agg.head()

,order_id,total_payment_value,max_installments,n_payment_methods
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,1
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,1
2,000229ec398224ef6ca0657da4fc703e,216.87,5,1
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,1

## zip code lookup table for distance (used later in notebook 5)

geolocation has many gps rows per zip code prefix - collapse to one row per prefix
(mean lat/lng). this isn't part of the ml table itself: computing an actual distance
from it is a derived feature (a haversine formula, not a plain count/sum), so that
calculation belongs in notebook 5, not here. this is just the aggregation notebook 5
will need to do it.

In [18]:
# drop a handful of points outside Brazil's rough bounding box before averaging, bad GPS data
geo_clean = geolocation[
    geolocation["geolocation_lat"].between(-34, 6)
    & geolocation["geolocation_lng"].between(-74, -32)
]

zip_geoloc = geo_clean.groupby("geolocation_zip_code_prefix").agg(
    lat=("geolocation_lat", "mean"),
    lng=("geolocation_lng", "mean"),
).reset_index().rename(columns={"geolocation_zip_code_prefix": "zip_code_prefix"})

zip_geoloc.to_csv(ARTIFACTS_DIR / "01_zip_geoloc.csv", index=False)
print("saved zip_geoloc:", zip_geoloc.shape)
zip_geoloc.head()

saved zip_geoloc: (19011, 3)

   zip_code_prefix        lat        lng
0             1001 -23.550190 -46.634024
1             1002 -23.548146 -46.634979
2             1003 -23.548994 -46.635731
3             1004 -23.549799 -46.634757
4             1005 -23.549456 -46.636733

## the ML table,one row per order

In [19]:
# start from orders (one row per order) and left-join everything else onto it,
# so the row count never grows past the number of orders
ml_table = orders.merge(
    customers[["customer_id", "customer_state", "customer_zip_code_prefix"]],
    on="customer_id", how="left",
)

for agg_df in [items_agg, main_seller, weight_agg, main_category, payments_agg, main_payment_type]:
    ml_table = ml_table.merge(agg_df, on="order_id", how="left")

ml_table = ml_table.merge(
    sellers[["seller_id", "seller_state", "seller_zip_code_prefix"]],
    left_on="main_seller_id", right_on="seller_id", how="left",
).drop(columns="seller_id")

ml_table.shape

(99441, 25)

## check the ML table

In [20]:
print("orders rows:", len(orders), "| ml_table rows:", len(ml_table))
print("duplicate order_id in ml_table:", ml_table["order_id"].duplicated().sum())

nulls = ml_table.isna().sum()
print("\nnulls per column (only where > 0):")
print(nulls[nulls > 0])

orders rows: 99441 | ml_table rows: 99441
duplicate order_id in ml_table: 0

nulls per column (only where > 0):
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
n_items                           775
n_distinct_products               775
n_distinct_sellers                775
total_price                       775
total_freight_value               775
avg_item_price                    775
main_seller_id                    775
total_weight_g                    775
main_product_category            2194
total_payment_value                 1
max_installments                    1
n_payment_methods                   1
main_payment_type                   1
seller_state                      775
seller_zip_code_prefix            775
dtype: int64

In [21]:
ml_table.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
 8   customer_state                 99441 non-null  str
 9   customer_zip_code_prefix       99441 non-null  int64
 10  n_items                        98666 non-null  float64
 11  n_distinct_products            98666 non-null  float64
 12  n_distinct_sellers             98666 non-null  float64
 13  total_price                    98666 non-null  float64
 14  total_freight_value            98666 non-null  float64
 15  avg_item_price                 98666 non-null  float64
 16  main_seller_id                 98666 non-null  str
 17  total_weight_g                 98666 non-null  float64
 18  main_product_category          97247 non-null  str
 19  total_payment_value            99440 non-null  float64
 20  max_installments               99440 non-null  float64
 21  n_payment_methods              99440 non-null  float64
 22  main_payment_type              99440 non-null  str
 23  seller_state                   98666 non-null  str
 24  seller_zip_code_prefix         98666 non-null  float64
dtypes: datetime64[us](5), float64(11), int64(1), str(8)
memory usage: 19.0 MB

## Save the artifact

In [22]:
out_path = ARTIFACTS_DIR / "01_ml_table.csv"
ml_table.to_csv(out_path, index=False)
print("saved:", out_path, "shape:", ml_table.shape)

saved: artifacts\01_ml_table.csv shape: (99441, 25)